url_shortener/models.py
import string
from datetime import datetime
from random import choices

from .extensions import db 

class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(512))
    short_url = db.Column(db.String(3), unique=True)
    visits = db.Column(db.Integer, default=0)
    date_created = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_link()

    def generate_short_link(self):
        characters = string.digits + string.ascii_letters
        short_url = ''.join(choices(characters, k=3))

        link = self.query.filter_by(short_url=short_url).first()

        if link:
            return self.generate_short_link()
        
        return short_url

url_shortener/__init__.py
from flask import Flask 

from .extensions import db
from .routes import short

def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)

    app.register_blueprint(short)

    return app

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect

from .extensions import db
from .models import Link

short = Blueprint('short', __name__)

@short.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()

    link.visits = link.visits + 1
    db.session.commit()

    return redirect(link.original_url) 

@short.route('/')
def index():
    return render_template('index.html') 

@short.route('/enter_link', methods=['POST'])
def add_link():
    original_url = request.form['original_url']
    link = Link(original_url=original_url)
    db.session.add(link)
    db.session.commit()

    return render_template('link_added.html', 
        new_link=link.short_url, original_url=link.original_url)

@short.route('/status')
def stats():
    links = Link.query.all()

    return render_template('status.html', links=links)

@short.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

url_shortener/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>URL Shortener</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    </head>

<body>
    <section class="section">
        <div class="container" >
            <style>
             h1{
                padding-top: 100px;
                align-content: center;
                text-align: center;
                font-family:'Times New Roman';
                font-style: italic;
                font-size: 50px;
                color:black;
            }
            .w3-btn {
                width:150px;
                background-color:green;
                color: white;
            }
            html{
                background-color: #cccccc;
            }
            form{
                align-content: center;
                padding-top: 100px;
                margin: auto;
            }
            div.control{
                display: flex;
                justify-content: center;
                text-align: center;
                padding-top: 30px;
            }

            div.field{
                display: flex;
                justify-content: center;
                font-size: 25px;
            }
            div.button{
                display: flex;
                justify-content: center;
                padding-top: 50px;
            }
            
            </style>

            <h1>Welcome to URL Shortener </h1>
            <form method="POST" action="{{ url_for('short.add_link') }}">
                <div class="field">
                    <label class="label">Enter Original URL</label>
                </div>

                <div class="control">
                        <input class="w3-input w3-border w3-animate-input" type="text" style="width:30%" name="original_url">
                </div>
                <div class="button">
                 <button type="submit" class="w3-btn w3-round-large">Submit</button>     
                </div>
            </form>
        </div>
    </section>
</body>

</html>

url_shortener/templates/link_added.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>URL Shortener</title>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>!
  </head>

  <body>
    
    <style>
      div.field{
        align-content: center;
        display: flex;
        justify-content: center;
        padding-top: 30px;
        text-align: center;
      }
      
      html{
        background-color: #cccccc;
      }
      
      div.control{
        align-content: center;
        display: flex;
        justify-content: center;
        padding-top: 10px;
        text-align: center;
      }
    </style>

    <section class="section">
    <div class="field">
      <label class="label">Original URL</label>
    </div>
    
    <div class="control">
      <input class="input" type="text" name="original_url" value="{{ original_url }}">
    </div>
    
    <div class="field">
      <label class="label">New URL</label>
    </div>
    
    <div class="control">
      <input class="input" type="text" name="original_url" value="{{ url_for('short.redirect_to_url', short_url=new_link, _external=True) }}">
    </div>
  </section>
  </body>
</html>

url_shortener/templates/status.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>URL Shortener</title>
</head>



<body>
    <style>
        td{
            padding-right: 20px;
            padding-top: 30px;
            padding-left: 20px;
        }
        
        html{
            background-color: #cccccc;
        
        }
        tr{
            padding-top: 30px;
            color:black;
        }
    </style>
    <section class="section">
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th>Original URL</th>
                        <th>Shorted URL</th>
                        <th>Visits</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for link in links %}
                    <tr>
                        <td>{{ link.original_url }} </td>
                        <td>{{ url_for('short.redirect_to_url', short_url=link.short_url, _external=True) }}</td>
                        <td>{{ link.visits }} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
</body>

</html>